Feature/display
BrewBlox/brewblox-firmware pull request #291
Opened 2021-08-13 13:52 UTC by CvRXX

**fixing issues with graphics including:**

- docs
- Background color matching
- Textsizing
- Led for the pid
- Naming

2021-08-14 12:50 UTC, elcojacobs requested changes
Some small code quality issues

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/bar.hpp
> +     * @param maincontainer the maincontainer in which the bar will be drawn.
doc/code case mismatch

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/bar.hpp
> +     * Enables or disables the wifi. If enabled the ip will be shown.
Confusing comment: Sets wifi icon state, doesn't disable wifi.

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/bar.hpp
> +     * Enables or disables the ethernet. If enabled the ip will be shown.
Same

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/graphics.hpp
> +    /// Updates the latout with new information.
typo.
which new info? where does it come from? This comment adds very little.

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/graphics.hpp
> +    /// Updates all it's widgets with new information.
it's -> its, same comment as above

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/graphics.hpp
> +    // A pointer to the top bar.
unnecessary comment

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/ActuatorAnalogWidget.hpp
> +        value = lv_label_create(obj, NULL);
prefer nullptr in c++

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/ActuatorAnalogWidget.hpp
> +        if (this->getLuminance() > (255 / 2)) {
can be simplified perhaps by writing something like:
`auto& color = getLuminance() > (255 / 2) ? LV_COLOR_BLACK : LV_COLOR_WHITE;`

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/BaseWidget.cpp
> +    return 0.2126 * color.ch.red + 0.7152 * color.ch.green + 0.0722 * color.ch.blue;
Avoid floating point.
`(uint16_t{54} * color.ch.red + uint16_t{183} * color.ch.green + uint16_t{18} * color.ch.blue) / 256;`

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/PidWidget.hpp
> +    void setInputValue(std::string txt)
unnecessary copy, here and in other places. Use `const std::string& txt` or make arg const char*

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/PidWidget.hpp
> +    void setPBar(int32_t persentage)
It's not really a status bar, it is a value bar.
The filling? -> fill width
persentage? :open_mouth:
I would say fill left and right here.

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/PidWidget.hpp
> +    void setActive(bool state)
if it just sets the LED, shouldn't the function be called setLed?

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/PidWidget.hpp
> +        lv_label_set_text(outputValue, "-");
Alignment is set here and overwritten by setters.
Probably setters should not re-align the object because the alignment seems static?

A lot of code is duplicated in both the makeObj init and later setters. 
Init can set the static values and use the setters for the dynamic values.

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/PidWidget.hpp
> +                setInputValue(temp_to_string(input->value(), 1, tempUnit));
why not let setInputValue take a temp as argument and do the conversion there?

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/TemperatureWidget.hpp
> +#include <esp_log.h>
leftover esp_log include

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/TemperatureWidget.hpp
> +/// A widget which represents an analog actuator.
copy/paste comment without modifying it

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/TemperatureWidget.hpp
>      TemperatureWidget(lv_obj_t* grid, const cbox::CboxPtr<TempSensor> ptr, const char* label, lv_color_t color)
CboxPtr argument should be rvalue or const ref, not const pass by value.
I think rvalue is correct here.

2021-08-14 12:50 UTC, elcojacobs commented on platform/all/graphics/widgets/TemperatureWidget.hpp
> +        if (this->getLuminance() > (255 / 2)) {
why not just type 128 here?
This logic also belongs in the base class I think.

2021-08-15 12:48 UTC, CvRXX commented on platform/all/graphics/widgets/PidWidget.hpp
> +                setInputValue(temp_to_string(input->value(), 1, tempUnit));
I didn't do that because of the option for a value to be `-`. One could make a different function to set if the temperature is valid or not but I don't think that will be an improvement.

2021-08-19 16:47 UTC, elcojacobs requested changes
Some small spelling errors still remain, but otherwise looks good. Will test on hw and merge.
Can we use .c extension for the fonts to avoid warnings about designated initializers or disable the warnings for just these files?

2021-08-19 16:47 UTC, elcojacobs commented on platform/all/graphics/bar.hpp
> +/// A topbar for the display
top bar

2021-08-19 16:47 UTC, elcojacobs commented on platform/all/graphics/bar.hpp
> +     * Constructs the bar and it's components. Also sets the bar text to it's initial values.
its

2021-08-19 16:47 UTC, elcojacobs commented on platform/all/graphics/graphics.hpp
> +/// Represents the graphics for the pyschical screen of the brewblox system.
physical
But better: TFT screen of the Spark 4

2021-08-19 16:47 UTC, elcojacobs commented on platform/all/graphics/graphics.hpp
> +/// A structure that holds the layout of the screen and it's children.
its. This is possessive, not it is

2021-08-19 16:47 UTC, elcojacobs commented on platform/all/graphics/widgets/BaseWidget.hpp
> +    /// Returns the redness of the background color.S
.S ?

2021-08-19 16:47 UTC, elcojacobs commented on platform/all/graphics/widgets/PidWidget.hpp
> +        if (this->getRed() > (255 / 2)) {
128

2021-08-19 21:16 UTC, elcojacobs commented
- use `npx lv_font_conv` make the script work without installing the npm package
- did you compare the compression/format options?
- Should we bundle all fonts in a single one? Or split into an icon font and roboto font?
- Split the long line in the python script into multiple lines
- Remove unused imports from python script
- Use c files for fonts to avoid warnings about incompatible fonts
- We have many font sizes, should we? Why not include only the ones that are used?
- Can we use a wifi icon with different bars for strength? material icons has wifi-strength-1 to 4

2021-08-23 13:46 UTC, merged