Feature/lvgl v8.2.0
BrewBlox/brewblox-firmware pull request #365
Opened 2022-03-07 12:42 UTC by CvRXX

This PR bumps LVGL to the v8.2.0 version. The functionality should be exactly the same as on `develop`. 

The biggest change in code is that the layout of the blocks is now done with the new grid feature which removes a lot of boilerplate.

2022-03-07 14:44 UTC, steersbob commented
Can't say much about the C++ side of things, so mostly notes to keep config clean.

2022-03-07 14:49 UTC, steersbob requested changes

2022-03-07 14:49 UTC, steersbob commented on .devcontainer/Dockerfile
> +        nodejs \
this list is sorted alphabetically

2022-03-07 14:49 UTC, steersbob commented on app/brewblox-esp/sdkconfig
> +
Looks like lvgl snuck into sdkconfig again. Is it intentional this time?

2022-03-07 14:49 UTC, steersbob commented on platform/all/graphics/fonts/generate_fonts.py
>  os.system(
Typically, `subprocess.run([*args])` is preferable to os.system, but this is not critical.

2022-03-07 14:49 UTC, steersbob commented on .devcontainer/Dockerfile
> +    && npm i lv_font_conv -g \
Put installed packages on an indented new line. This significantly increases readability of both the Dockerfile itself, and future diffs.
```
&& npm install -g \
    lv_font_conv \
```

2022-03-07 15:48 UTC, CvRXX commented on .devcontainer/Dockerfile
> +    && npm i lv_font_conv -g \
fixed in 70720752a92e85ad1286e4f6bff4dab053b3d1e0

2022-03-07 15:48 UTC, CvRXX commented on .devcontainer/Dockerfile
> +        nodejs \
fixed in 70720752a92e85ad1286e4f6bff4dab053b3d1e0

2022-03-07 15:48 UTC, CvRXX commented on app/brewblox-esp/sdkconfig
> +
fixed in 0c6fc0536ff469cfedc4f494f5bdfbcf6d57e38f

2022-03-10 14:21 UTC, elcojacobs approved these changes

2022-03-10 14:21 UTC, elcojacobs commented on platform/all/graphics/layout.cpp
>          auto makeWidget = [&settings, this](uint8_t pos) -> std::unique_ptr<BaseWidget> {
lamda is constructed and destructed. Maybe make static const and pass captures as args?

2022-03-10 14:21 UTC, elcojacobs commented on platform/all/graphics/widgets/BaseWidget.cpp
> +    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, 4);
is -4 to 4 intentional?

2022-03-15 10:57 UTC, CvRXX commented on platform/all/graphics/widgets/BaseWidget.cpp
> +    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, 4);
Yes, it is, I think the alignment functions changed.

2022-03-16 14:54 UTC, elcojacobs requested changes
trailing return type on function not in line with rest of code base

2022-03-16 17:39 UTC, merged