Refactor IO modules and discovery
BrewBlox/brewblox-firmware pull request #440
Opened 2022-10-10 12:54 UTC by elcojacobs

- Separates GPIO into a separate class instead of inside GPIO + OneWire class, so it can be re-used.
- Moves OneWire discovery into blocks instead of platform factory
- Refactored balancer to resolve valgrind warnings in tests. Balancer now has requester block ID in clients list, so the constraint itself doesn't need an id.

2022-10-11 11:56 UTC, steersbob requested changes

2022-10-11 11:56 UTC, steersbob commented on lib/blocks/src/ConstraintsProto.cpp
> +using Balanced_t = AAConstraints::Balanced<blox_Constraints_AnalogConstraint_balanced_tag, cbox::obj_id_t>;
consistent naming of typedef / using?

2022-10-11 11:56 UTC, steersbob commented on lib/blocks/src/OneWireBusBlock.cpp
> +    if (iface == cbox::interfaceId<cbox::ScanningFactory>()) {
Block read/write can become noop functions.

2022-12-27 13:25 UTC, elcojacobs commented on lib/blocks/src/OneWireBusBlock.cpp
> +    if (iface == cbox::interfaceId<cbox::ScanningFactory>()) {
will do that in another PR that refactors onewire

2023-01-03 12:34 UTC, steersbob approved these changes

2023-01-03 12:34 UTC, merged