Use IO channels as digital input, refactor IO channels and fault handling
BrewBlox/brewblox-firmware pull request #503
Opened 2023-06-25 22:08 UTC by elcojacobs

Still to do:
- Sequence block integration
- Input modes instant/toggle/pulse
- Hardware testing

Done:
- Refactored how faults are handled and reported for IO channels, now also faults per channel if applicable
- Added simulation for openload and overcurrent
- IoChannelPtr is now the only holder of the channel number
- Block factories are now static constexpr
- Many clang-tidy fixes

2023-06-26 11:24 UTC, steersbob requested changes

2023-06-26 11:24 UTC, steersbob commented on lib/control/inc/control/ActuatorDigital.hpp
Rename to `DigitalActuator` to match the interface and `DigitalInput`?

2023-06-26 11:24 UTC, steersbob commented on lib/control/inc/control/MockIoArray.hpp
> +                ;
empty statement.

2023-06-26 11:24 UTC, steersbob commented on lib/control/inc/control/MotorValve.hpp
> +    ControlPtr<DS2408> _target;
Not an IoChannelPtr?

2023-06-26 11:24 UTC, steersbob commented on lib/control/inc/control/OneWireDevice.hpp
>      ControlPtr<OneWire> m_bus;
Can be renamed to `_bus`, if this file is being edited anyway.

2023-06-26 11:24 UTC, steersbob commented on lib/control/src/DigitalInput.cpp
> + * Copyright 2013 BrewPi/Elco Jacobs.
Outdated copyright header

2023-06-26 11:24 UTC, steersbob commented on lib/control/src/DigitalInput.cpp
> +// duration_millis_t DigitalInput::update()
dead code

2023-06-26 11:24 UTC, steersbob commented on test/blocks/DigitalInputBlock_test.cpp
> + * Copyright 2018 BrewPi B.V.
More outdated headers. You can also just omit them until we get it fixed automatically.

2023-06-26 11:24 UTC, steersbob commented on test/blocks/DigitalInputBlock_test.cpp
> +    cbox::update();
Use `test::update(0, 0)` to set both utc and context::now()

2023-06-26 11:24 UTC, steersbob commented on test/blocks/GpioModule_test.cpp
> + * Copyright 2018 BrewPi B.V.
Header again

2023-06-26 11:24 UTC, steersbob commented on test/blocks/GpioModule_test.cpp
> +    cbox::update();
use `test::update(0, 0)`

2023-06-26 11:26 UTC, elcojacobs commented on .devcontainer/.bash_aliases
> +alias get_idf=". /opt/esp/idf/export.sh" && sudo ln -s "$(which clang-format)" /usr/local/bin/clang-format
Adding it in the second RUN in the dockerfile (line 170) didn't work. I don't know why.

2023-06-26 11:34 UTC, elcojacobs commented on lib/blocks/src/DigitalActuatorBlock.cpp
> +    static_assert(blox_IoArray_TransitionDurationPreset_ST_OFF == static_cast<int>(SoftTransitionsPreset::ST_OFF));
It can't be templated and macros are nasty. This is just so it screens when one enum is updated but the counterpart is not.

2023-06-26 11:35 UTC, elcojacobs commented on lib/blocks/src/DigitalActuatorBlock.cpp
> +            auto channel = _actuator.channel();
it's a workaround for behavior that was handled by the IO pointer before. But you are right, just clearing it makes sense.

2023-06-26 11:43 UTC, elcojacobs commented on lib/control/inc/control/ActuatorDigital.hpp
then we should rename all our actuators in control. Block name is DigitalActuator. We agreed to use DigitalInput instead of InputDigital.

2023-06-26 11:45 UTC, elcojacobs commented on lib/control/inc/control/MotorValve.hpp
> +    ControlPtr<DS2408> _target;
No, because it uses 4 channels and expects a DS2408 in proto, this was more appropriate.

2023-06-26 12:33 UTC, steersbob approved these changes

2023-06-27 21:42 UTC, steersbob approved these changes

2023-06-28 01:07 UTC, merged